development:
  redis:
    host: localhost
    porta: 6379
    synchronize: false

test:
  redis:
    host: localhost
    porta: 6379
    synchronize: false

production:
  redis:
    host: localhost
    porta: 6379
    synchronize: false