user: leandro
group: leandro
chdir: "/home/leandro/ruby/ruby-on-rails-websocket"
log:   "/home/leandro/ruby/ruby-on-rails-websocket/log/thin.log"
environment: development
address: 0.0.0.0
port: 3000
pid: tmp/pids/thin.pid
max_conns: 50000
max_persistent_conns: 50000
require: []
timeout: 30
wait: 30
daemonize: true
tag: aovivo-eventos-api
onebyone: true
no-epoll: true